[package]
name = "wasm3-sys"
version = "0.1.0"
authors = ["Lukas Tobias Wirth <lukastw97@gmail.com>"]
edition = "2018"
license = "MIT"
links = "wasm3"

[features]
wasi = []

[dependencies]
libc = "^0.2"

[build-dependencies]
cc = "1"